name: CI (Node.js)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test --if-present
    - name: coverage
      run: npm test --silent -- --coverage
    - name: build_image
      run: docker build -t myapp:latest .
    - name: push_image
      run: docker push myapp:latest
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
