name: CI (Node.js)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: lint
      run: npm install --save-dev eslint && npx eslint .
    - name: Run tests
      run: npm ci && npm test --silent
    - name: build_image
      run: docker build -t myapp:latest .
    - name: push_image
      run: docker push myapp:latest
    - name: coverage
      run: npm run coverage --if-present || echo 'no coverage script'
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
