name: CI (Python)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: black --check .
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi'
    - name: Run tests
      run: pytest -q || true
    - name: build_image
      run: docker build -t myapp:latest .
    - name: push_image
      run: docker push myapp:latest
    - name: coverage
      run: coverage run -m pytest && coverage report
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
