name: CI (Rust)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
    - name: build_image
      run: docker build -t myapp:latest .
    - name: push_image
      run: docker push myapp:latest
    - name: coverage
      run: cargo llvm-cov --all-features --workspace --summary-only && cargo llvm-cov
        --all-features --workspace --lcov --output-path lcov.info
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}
