name: CI (Rust)
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: build_image
      run: docker build -t myapp:latest .
    - name: push_image
      run: docker push myapp:latest
    - name: push_image
      run: docker push myapp:latest
    - name: push_image
      run: docker push myapp:latest
    - name: coverage
      run: go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out
        && go tool cover -html=coverage.out -o coverage.html
    - name: build_image
      run: docker build -t myapp:latest .
    - name: coverage
      run: go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out
        && go tool cover -html=coverage.out -o coverage.html
    - name: build_image
      run: docker build -t myapp:latest .
    - name: coverage
      run: go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out
        && go tool cover -html=coverage.out -o coverage.html
